/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: de374ca05edbeba339e6f4e2894a7b9c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "CodeGeneratorAgent" | "UserAppSandboxService" | "DORateLimitStore" | "UserSecretsStore";
	}
	interface Env {
		VibecoderStore: KVNamespace;
		ALLOWED_EMAIL: "choijjames@gmail.com";
		DISPATCH_NAMESPACE: "vibesdk-default-namespace";
		ENABLE_READ_REPLICAS: "true";
		PLATFORM_CAPABILITIES: {"features":{"app":{"enabled":true},"presentation":{"enabled":false},"general":{"enabled":false}},"version":"1.0.0"};
		MAX_SANDBOX_INSTANCES: "10";
		SANDBOX_INSTANCE_TYPE: "standard-3";
		CUSTOM_DOMAINS: "vibesdk.megabyte.app,vibesdk-web.megabyte.app";
		CUSTOM_DOMAIN: string;
		ENVIRONMENT: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_AI_GATEWAY_TOKEN: string;
		CLOUDFLARE_AI_GATEWAY_URL: string;
		ANTHROPIC_API_KEY: string;
		OPENAI_API_KEY: string;
		GOOGLE_AI_STUDIO_API_KEY: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		GITHUB_EXPORTER_CLIENT_ID: string;
		GITHUB_EXPORTER_CLIENT_SECRET: string;
		JWT_SECRET: string;
		WEBHOOK_SECRET: string;
		USE_TUNNEL_FOR_PREVIEW: string;
		CLOUDFLARE_AI_GATEWAY: string;
		TEMPLATES_REPOSITORY: string;
		AI_PROXY_JWT_SECRET: string;
		ALLOCATION_STRATEGY: string;
		CF_ACCESS_ID: string;
		CF_ACCESS_SECRET: string;
		CUSTOM_PREVIEW_DOMAIN: string;
		"env.SANDBOX_SERVICE_TYPE": string;
		SANDBOX_SERVICE_API_KEY: string;
		SANDBOX_SERVICE_URL: string;
		SENTRY_AUTH_TOKEN: string;
		SENTRY_DSN: string;
		USE_CLOUDFLARE_IMAGES: string;
		VITE_SENTRY_DSN: string;
		CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
		Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
		DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
		UserSecretsStore: DurableObjectNamespace<import("./worker/index").UserSecretsStore>;
		TEMPLATES_BUCKET: R2Bucket;
		DB: D1Database;
		DISPATCHER: DispatchNamespace;
		API_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
		AI: Ai;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_EMAIL" | "DISPATCH_NAMESPACE" | "ENABLE_READ_REPLICAS" | "PLATFORM_CAPABILITIES" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "CUSTOM_DOMAINS" | "CUSTOM_DOMAIN" | "ENVIRONMENT" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_AI_GATEWAY_TOKEN" | "CLOUDFLARE_AI_GATEWAY_URL" | "ANTHROPIC_API_KEY" | "OPENAI_API_KEY" | "GOOGLE_AI_STUDIO_API_KEY" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "GITHUB_EXPORTER_CLIENT_ID" | "GITHUB_EXPORTER_CLIENT_SECRET" | "JWT_SECRET" | "WEBHOOK_SECRET" | "USE_TUNNEL_FOR_PREVIEW" | "CLOUDFLARE_AI_GATEWAY" | "TEMPLATES_REPOSITORY" | "AI_PROXY_JWT_SECRET" | "ALLOCATION_STRATEGY" | "CF_ACCESS_ID" | "CF_ACCESS_SECRET" | "CUSTOM_PREVIEW_DOMAIN" | "env.SANDBOX_SERVICE_TYPE" | "SANDBOX_SERVICE_API_KEY" | "SANDBOX_SERVICE_URL" | "SENTRY_AUTH_TOKEN" | "SENTRY_DSN" | "USE_CLOUDFLARE_IMAGES" | "VITE_SENTRY_DSN">> {}
}
